ignore: null
task: segmentation
tiled_inference_on_testing: false
tiled_inference_on_validation: false
path_to_record_metrics: null
model_args:
  backbone_pretrained: true
  backbone: prithvi_eo_v2_300_tl
  backbone_coords_encoding:
  - time
  - location
  backbone_bands:
  - BLUE
  - GREEN
  - RED
  - NIR_NARROW
  - SWIR_1
  - SWIR_2
  backbone_num_frames: 3
  decoder: UperNetDecoder
  decoder_channels: 256
  decoder_scale_modules: true
  num_classes: 13
  head_dropout: 0.1
  necks:
  - name: SelectIndices
    indices:
    - 5
    - 11
    - 17
    - 23
  - name: ReshapeTokensToImage
    effective_time_dim: 3
  rescale: true
model_factory: EncoderDecoderFactory
model: null
loss: ce
aux_heads: null
aux_loss: null
class_weights:
- 0.386375
- 0.661126
- 0.548184
- 0.640482
- 0.876862
- 0.925186
- 3.249462
- 1.542289
- 2.175141
- 2.272419
- 3.062762
- 3.626097
- 1.198702
ignore_index: -1
lr: 0.0002
optimizer: AdamW
optimizer_hparams:
  weight_decay: 0.1
scheduler: null
scheduler_hparams: null
freeze_backbone: false
freeze_decoder: false
freeze_head: false
plot_on_val: false
class_names: null
tiled_inference_parameters: null
test_dataloaders_names: null
lr_overrides: null
output_on_inference: prediction
output_most_probable: true
