seed_everything: 0
# trainer:
#   accelerator: auto
#   strategy: auto
#   devices: auto
#   num_nodes: 1
#   precision: 16-mixed
#   logger:
#     class_path: TensorBoardLogger
#     init_args:
#       save_dir: <your_dir>
#       name: trainer_name
#   callbacks:
#     - class_path: RichProgressBar
#     - class_path: LearningRateMonitor
#       init_args:
#         logging_interval: epoch
#     - class_path: lightning.pytorch.callbacks.EarlyStopping
#       init_args:
#         patience: 20
#         monitor: val/loss
#   max_epochs: 125
#   check_val_every_n_epoch: 10
#   log_every_n_steps: 50
#   enable_checkpointing: True
#   default_root_dir: <your_dir>

data:
  class_path: MultiTemporalCropClassificationDataModule
  init_args:
    batch_size: 8
    num_workers: 12
    reduce_zero_label: True
    expand_temporal_dimension: True
    use_metadata: True
    bands:
      - BLUE
      - GREEN
      - RED
      - NIR_NARROW
      - SWIR_1
      - SWIR_2
    train_transform:
      - class_path: FlattenTemporalIntoChannels
      - class_path: albumentations.Flip
      - class_path: ToTensorV2
      - class_path: UnflattenTemporalFromChannels
        init_args:
          n_timesteps: 3
    val_transform:
      - class_path: FlattenTemporalIntoChannels
      - class_path: albumentations.Flip
      - class_path: ToTensorV2
      - class_path: UnflattenTemporalFromChannels
        init_args:
          n_timesteps: 3
    data_root: /dccstor/geofm-finetuning/hls_cdl_reclassed # https://huggingface.co/ibm-nasa-geospatial/Prithvi-EO-1.0-100M-multi-temporal-crop-classification


model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_args:
      # backbone_pretrained: False
      # backbone: <prithvi_model> # prithvi_vit_100, prithvi_eo_v2_300, prithvi_eo_v2_300_tl, prithvi_eo_v2_600, prithvi_eo_v2_600_tl
      backbone: prithvi_eo_v2_300_tl
      decoder: UperNetDecoder
      num_classes: 13
      backbone_pretrained: True
      backbone_coords_encoding:
        - "time"
        - "location"
      rescale: True
      backbone_bands:
        - BLUE
        - GREEN
        - RED
        - NIR_NARROW
        - SWIR_1
        - SWIR_2
      head_dropout: 0.1
      decoder_channels: 256
      backbone_num_frames: 3
      necks:
        - name: SelectIndices
          indices:
            # indices for prithvi_vit_100
            # - 2
            # - 5
            # - 8
            # - 11
            # indices for prithvi_eo_v2_300
            - 5
            - 11
            - 17
            - 23
            # indices for prithvi_eo_v2_600
            # - 7
            # - 15
            # - 23
            # - 31
        - name: ReshapeTokensToImage
          effective_time_dim: 3
    loss: ce
    ignore_index: -1
    class_weights:
      - 0.386375
      - 0.661126
      - 0.548184
      - 0.640482
      - 0.876862
      - 0.925186
      - 3.249462
      - 1.542289
      - 2.175141
      - 2.272419
      - 3.062762
      - 3.626097
      - 1.198702
    freeze_backbone: false
    freeze_decoder: false
    model_factory: EncoderDecoderFactory

# optimizer:
#   class_path: torch.optim.AdamW
#   init_args:
#     lr: 0.0003
#     weight_decay: 0.35

# lr_scheduler:
#   class_path: StepLR
#   init_args:
#     step_size: 10
#     gamma: 0.9